export const PROJECT_CREATION_START = "PROJECT_CREATION_START";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const ADD_ANOTHER_PROJECT = "ADD_ANOTHER_PROJECT";

export const LOGIN_SUCCESSFULL = "LOGIN_SUCCESSFULL";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_FLAG_SETTER = "LOGIN_FLAG_SETTER";

export const QR_UPLOAD = "QR_UPLOAD";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNUP_FLAG_SETTER = "SIGNUP_FLAG_SETTER";

export const NAV_ACTION_LOADER = "NAV_ACTION_LOADER";
